### ISSUE TITLE
Url is wrong

### ISSUE THREAD

**Issue by zjb0807** [paritytech/srtool#21]
https://github.com/paritytech/srtool/blob/a88c728674b98da14963ca60d18444fe691cf654/.github/workflows/manual-acala.yml#L61
```
wget https://github.com/chevdor/subwasm/releases/download/v${{ SUBWASM_VERSION }}/subwasm_linux_amd64_v${{ SUBWASM_VERSION }}.deb 
```

**Comment by chevdor** [comment]
Can you explain what you mean ?

**Comment by chevdor** [comment]
Oh I see what you mean. That should only affect the tests but I will fix that asap. Thanks for the fast report !
