### ISSUE TITLE
Add a --features option or modify --default-features to enable any runtime

### ISSUE THREAD

**Issue by librelois** [paritytech/srtool#24]
Currently, the `--default-features` option allows to modify the list of features that are passed to cargo, but only for the polkadot and kusama runtime.

## Need

In our use case (moonbeam project), we need to be able to build our runtime with an optional tracing feature reserved to our tracing nodes, we would like to be able to build our runtimes with srtool.
For the moment we have to modify the Cargo.toml before each build to add our tracing features in default, it's dirty.

## Proposal

Rename the `--default-features` option to `--features` (with the old name as an alias to keep compatibility). And remove the filter that reserves this option for polkadot and kusama.

**Comment by chevdor** [comment]
Salut Éloïs :)

I think you mean to report this issue for [this repo](https://github.com/chevdor/srtool-cli), don't you ?

The srtool **docker image**  only support passing ENV to docker.
So if your question is about the `srtool` **docker image**, you can try passing your opts as `BUILD_OPTS`, this takes over the default behavior you noticed for Polkadot and Kusama.

If you mean to report an issue for the `srtool-cli`, I would ask you to close this issue and open one in the [appropriate repo](https://github.com/chevdor/srtool-cli).

With the cli, I think you can solve your problem using the `--build-opts` flag.

Can you please confirm whether you are using the docker image directly or via the srtool-cli and if the solutions above allow you to solve your problem ?

**Comment by chevdor** [comment]
Closing this issue now as I think you have solutions above. Feel free to re-open if you are still stuck.
