### ISSUE TITLE
Regression: new rootless version doesn't work for regular users

### ISSUE THREAD

**Issue by bernardo-xxnet** [paritytech/srtool#46]
When developing on a local Ubuntu machine (not CI), the new srtool version always fails with

```
error: failed to create directory `/build/runtime/xxnetwork/target`

Caused by:
  Permission denied (os error 13)
```

Project: https://github.com/xx-labs/xxchain
Runtime: `/runtime/xxnetwork`
Build command:  `srtool build --package xxnetwork-runtime`
Expanded command:
```
docker run --name srtool --rm -e PACKAGE=xxnetwork-runtime -e RUNTIME_DIR=runtime/xxnetwork -e BUILD_OPTS= -e DEFAULT_FEATURES= -e PROFILE=release -e IMAGE=d5353a63d8fccbef5666e28a8fa0b302d71d4f53cabeb760fe213f3d7df4b8b6 -v /home/bernie/xxchain:/build -v /tmp/cargo:/cargo-home paritytech/srtool:1.62.0 build
```

When manually running the previous srtool version everything works as intended:
Command:
```
docker run --name srtool --rm -e PACKAGE=xxnetwork-runtime -e RUNTIME_DIR=runtime/xxnetwork -e BUILD_OPTS= -e DEFAULT_FEATURES= -e PROFILE=release -e IMAGE=1b8a407425fdfa86a3c660c674f5fbb80e7105551ec75977db9c682c1c8f3b00 -v /home/bernie/xxchain:/build -v /tmp/cargo:/cargo-home paritytech/srtool:1.60.0 build
```

It seems that the builder user never has permissions to write the target output folder back to the calling user's directories. I have tried to pass my user with `-e BUILDER=user` and also running the docker command in sudo, but none works.

**Comment by bernardo-xxnet** [comment]
Hey @chevdor thanks for the quick reply!

I had removed the `target` folder.
Using `--user root` it compiles (nice!), except for this small issue of not being able to determine git commit/tag/branch:
```
fatal: unsafe repository ('/build' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /build
fatal: unsafe repository ('/build' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /build
fatal: unsafe repository ('/build' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /build
Summary generated with srtool v0.9.21 using the docker image paritytech/srtool:1.62.0:
 Package     : xxnetwork-runtime v0.2.3
 GIT commit  :
 GIT tag     :
 GIT branch  :
 Rustc       : rustc 1.62.0 (a8314ef7d 2022-06-27)
 Time        : 2022-07-07T15:28:41Z
 ```

**Comment by chevdor** [comment]
You can also test the following to make it work as rootless: rebuild the image using the following build args:
```
docker build .... --build-arg UID=$(id -u) --build-arg GID=$(id -g) ...
```

That will align the IDs of the container with your local system.

**Comment by chevdor** [comment]
@bernardo-xxnet here is an alternate (and new) option but this not official yet.
You could try re-installing the `srtool-cli` from [this branch](https://github.com/chevdor/srtool-cli/tree/wk-220822-run-as-root) and call it using `srtool build --root ....`. That should also fix your issue without having to rebuild the srtool image.
Could you confirm it solves your issue ?

**Comment by bernardo-xxnet** [comment]
Hey @chevdor 

I can confirm the new changes solve my issue!

I made it work with a hack at the time of my original comment, I forgot to update here.
The UID being used by the docker image is 1000, which matched my user already, but docker runs under the `docker` group, which my user is part of.
The GID used in the srtool image is 1001, which luckily matches the GID of the `docker` group on my machine. So what I did was `chgrp docker -R runtime` to allow the docker group to modify the runtime directory. That was the easiest way I found to solve it without needing to rebuild the docker image.
I also used this same procedure on other machines where the docker group has a different GID. In those cases I first changed the GID to be 1001.

Anyways, looking forward to the new `--root` flag making into a `srtool-cli` release.
Thanks!

**Comment by chevdor** [comment]
Yes tweaking the UID/GID is a way to go but that require a rebuild of the image and whatever default I use will always be wrong for someone. Thanks for documenting your issue/solution and confirming that the fix in my srtool-cli branch works for you. I will merge that and make a new release. I will keep this issue open until the option is officially available in the next srtool-cli.

**Comment by tmpolaczyk** [comment]
I get the same error on commit 8f991d6fc4ca4557b922c23bbb4a407253f1109d 

Was this issue never fixed?

I can confirm that running `srtool build --root` fixes the error.

**Comment by bkchr** [comment]
> I can confirm that running `srtool build --root` fixes the error.

Same for me. @chevdor this isn't really any nice UX if you need to find this issue to fix this. Can `srtool` not detect this on its own?
